#!/bin/bash
# this is the script for assignment 1
# created by dennis on Feb 6 through 9, 2025
# it produces a report and takes no input

# gather the data
mydate=$(date)
myusername=$(whoami)
# the p option filters extra data out of the uptime default output
myuptime=$(uptime -p)
# we can get the OS info from the /etc/os-release script
source /etc/os-release
mydistro="$PRETTY_NAME"

# Produce the final report
cat <<EOF

System Report generated by $myusername, $mydate
 
System Information
------------------
Hostname: $HOSTNAME
      OS: $mydistro
  Uptime: $myuptime

EOF

