#!/bin/bash

# This script is for assignment 1, create a system report
# started October 9, 2024 by dennis
# We need to gather a bunch of data, then format it in a report

# the first line might be generated using:
#     echo "System report generated by $USER, $(date)"

# we have a lot of lines to produce, so we will use a template instead of generating one output line at a time

#######
# gather data into variables
#######
myusername="$USER"
currentdatetime="$(date)"

# we get the distro name and version from /etc/os-release
# this won't work on computer's without an /etc/os-release file!!!
source /etc/os-release
mydistro="$PRETTY_NAME"

#######
# produce report from template
#######
cat <<EOF

System Report generated by $myusername, $currentdatetime
 
System Information
------------------
Hostname: HOSTNAME
OS: $mydistro
Uptime: UPTIME
 
Hardware Information
--------------------
cpu: PROCESSOR MAKE AND MODEL
Speed: CURRENT AND MAXIMUM CPU SPEED
Ram: SIZE OF INSTALLED RAM
Disk(s): MAKE AND MODEL AND SIZE FOR ALL INSTALLED DISKS
Video: MAKE AND MODEL OF VIDEO CARD
 
Network Information
-------------------
FQDN: FQDN
Host Address: IP ADDRESS FOR THE HOSTNAME
Gateway IP: GATEWAY ADDRESS
DNS Server: IP OF DNS SERVER
 
InterfaceName: MAKE AND MODEL OF NETWORK CARD
IP Address: IP Address in CIDR format
 
System Status
-------------
Users Logged In: USER,USER,USER...
Disk Space: FREE SPACE FOR LOCAL FILESYSTEMS IN FORMAT: /MOUNTPOINT N
Process Count: N
Load Averages: N, N, N
Memory Allocation: DATA FROM FREE
Listening Network Ports: N, N, N, ...
UFW Rules: DATA FROM UFW SHOW

EOF

